server_host: 'chat.freenode.net'
server_port: 6666
nickname: zgphp
username: zgphp
password: <password>
realname: 'ZgPHP bot'

plugins:
    - AutoJoin
    - Meetup
    - PingPong
    - Weather
    - WebChecker

autojoin:
    channels:
        - "#zgphp"

meetup:
    api_key:
    group_id:

twitter:
    consumer_key:
    consumer_secret:
    access_token:
    access_token_secret:

    channel: "#zgphp"
    delay: 60
    query: "#zgphp OR @zgphp"

webchecker:
    channel: "#zgphp"
    check_delay: 60
    resend_delay: 1200
    urls:
        - http://zgphp.org/
        - http://2013.zgphp.org/
